# Generated by Django 4.2 on 2024-11-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetcategorydetails',
            old_name='asset',
            new_name='asset_based_id',
        ),
        migrations.AddField(
            model_name='assetcategorydetails',
            name='asset_number',
            field=models.IntegerField(default=0),
        ),
    ]
