# Generated by Django 4.2 on 2024-11-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_rename_asset_assetcategorydetails_asset_based_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcategorydetails',
            name='asset_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
