# Generated by Django 4.2 on 2024-11-13 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_alter_assetcategorydetails_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assetcategorydetails',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='EmployeeAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.usermaster')),
            ],
        ),
    ]
