# Generated by Django 4.2 on 2024-11-13 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_alter_assetcategorydetails_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeauth',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='employeeauth',
            name='employee',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='auth', to='assets.usermaster'),
            preserve_default=False,
        ),
    ]
